### ISSUE TITLE
Create readme documentation.

### ISSUE THREAD

**Issue by cesardeazevedo** [bitvagas/bitvagas#4]
Its time to document it.

* [x] Name
* [x] Project overview
* [x] Tools that we use
* [x] Usage
* [x] Contributions
* [x] License

**Comment by randsonjs** [comment]
:+1:

**Comment by cesardeazevedo** [comment]
Now, anyone can setup and run the application, i'll improve with more details... :smile:

**Comment by Anderson-Juhasc** [comment]
:+1:
